# Generated by Django 4.2.11 on 2024-05-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
