# Generated by Django 4.2.11 on 2024-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_subtask_name_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
