# Generated by Django 4.2.11 on 2024-05-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_task_subtasks_list_alter_subtask_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks_list',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authapp.contact'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
