# Generated by Django 4.2.11 on 2024-05-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inProgress', 'In Progress'), ('awaitingFeedback', 'Awaiting Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
