# Generated by Django 4.2.11 on 2024-06-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
