# Generated by Django 4.2.11 on 2024-06-11 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categoryColor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authapp.category'),
        ),
    ]
