# Generated by Django 4.2.11 on 2024-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_task_categorycolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categoryColor',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
