# Generated by Django 4.2.11 on 2024-06-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_remove_task_categorycolor_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categoryColor',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
